global:
  image: ubuntu

  trigger:
    branch:
      - main

jobs:
  - name: touch test
    commands:
      - touch test.txt
    artifacts:
      - name: test
        path: ./test.txt

  - name: cat test
    commands:
      - cat test.txt
    resources:
      - name: test
        path: ./