# Nosana
nosana:
  # This would be a block on it's own with the restrictions that are 
	description: Build Nosana Documentation
	wallet: nosana1234...7890
	# Callback URL where to publish data, instead of only the Nosana frontend
	webhook: https:webhook.nosana.io/123/abc # Not supported yet, Future TODO?
  backend: IPFS # Arweave, S3

global: 
	market: nosana123...123
	# Image to be used with this pipeline
	# Define container per pipeline? 
	# TODO authentication for registries
	image: node16 #  exmpl: registry.hub.docker.com/node16

	# Git 
	trigger:
		branch: 
			- main
      - develop
		# TODO ITEM is to further define the trigger syntax that is branch independent.
	
	# Environment variables
	environment: 
	 APP_ENV: production # comment here about this var
	 SOME: other # 
	
	# Allow pipeline to stop if one job fails
	allow_failure: true # default: false

# Collection of commands that will run inside the container in order to 

jobs: # rename this to pipelines?

  # If jobs do not have a container defined, it will use the default nosana-image
  - name: build
    market: nosana567...123 # different market
	  commands:
     - npm ci
     - npm run generate
     - npm run build --output dist/
    image: node:16
    environment: # These vars are merged with the global variables instead of overridding them
      NODE_ENV: dev
    resources:
      - name: git-clone
        path: /workdir
    artifacts:
      - name: dist-folder
        path: ./dist/
      - name: node-modules
        path: ./node-modules/

  # If jobs do not have a container defined, it will use the default nosana-image
  - name: test
	  commands:
     - npm run lint
    resources:
      - node-modules
    allow_failure: true

  - name: deploy
	  commands:
     - s3 sync dist s3://my-bucket
    image: aws-s3
    trigger: 
			branch: 
        - main
    environment: # These vars are merged with the global variables instead of overridding them
      AWS_PROF: dev
    resources:
      - dist-folder
