nosana:
  description: Test Colors

global:
  image: ubuntu
  trigger:
    branch:
      - main
  environment:
    TERM: xterm-color
    FORCE_COLOR: "1"
    CLICOLOR: "1"
    CLICOLOR_FORCE: "1"

jobs:
  - name: test-colors
    commands: 
      - sh -c 'echo $CLICOLOR_FORCE'
      - sh -c 'echo $TERM'
      - sh -c 'echo $COLORTERM'
      - ls -al
      - ls -al --color