nosana:
  description: Test Simple Secrets

global:
  image: ubuntu
  secrets:
    - global.test  
  environment:
    TERM: xterm

jobs:
  - name: test-colors
    secrets:
      - SECRET_VALUE
    commands: 
      - echo $SECRET_VALUE
      - echo $test
