nosana:
  description: Test Colors

global:
  image: ubuntu
  trigger:
    - branch:
       - main
    - pull-request: true
    - pull_request: true
  environment:
    TERM: xterm
    FORCE_COLOR: "1"
    CLICOLOR: "1"
    CLICOLOR_FORCE: "1"

jobs:
  - name: test-colors
    commands: 
      - echo $CLICOLOR_FORCE
      - echo $TERM
      - ls -al
      - ls -al --color